### ISSUE TITLE
make[1]: *** [all] Error 2

### ISSUE THREAD

**Issue by insidenothing** [BMoreToken/bmorecoin#1]
[ 59%] Built target Wallet
make[1]: *** [all] Error 2
make: *** [build-release] Error 2
Error: Process completed with exit code 2.

**Comment by Wolf727** [comment]
> [ 59%] Built target Wallet make[1]: *** [all] Error 2 make: *** [build-release] Error 2 Error: Process completed with exit code 2.

what about tokenomics?

**Comment by insidenothing** [comment]
> 

BMoreCoin (BALTx)
Max Block Number 500,000,000.
Total number of available 18,446,744,073,709,551,616 BALTx
Difficulty Target is 60 Seconds.
BMoreToken (BALT)
Max Total Supply: 3,947,960 BALT
Holders: 18
Transfers: 40
Address: 0xbdd4f273c2b0f0b84a51bd733aac617d91159376

**Comment by Wolf727** [comment]
> > 
> 
> BMoreCoin (BALTx) Max Block Number 500,000,000. Total number of available 18,446,744,073,709,551,616 BALTx Difficulty Target is 60 Seconds. BMoreToken (BALT) Max Total Supply: 3,947,960 BALT Holders: 18 Transfers: 40 Address: 0xbdd4f273c2b0f0b84a51bd733aac617d91159376

when block explorer?

**Comment by insidenothing** [comment]
> 

a few days ago https://www.bmorecoin.com/blockchain_explorer.php?block=691b621aee689986d2ca4152707eef5389b6d22dfb0637531c3995dda87b5129
